# Github branch name for production environment
master:

  # Server hostname or IP address for deployment
  hostname: prod.example.host

  # SSH user to be used in deployment
  user: www-data

  # branch name
  stage: master
  
  # Path to deploy.
  deploy_path: /opt/easyengine/sites/ci.dev1.rt.gw/app/htdocs

  # Setting these options because of ssh-issues in GH actions.
  # Should not be needed in future, hopefully :fingers-crossed:
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no

# Github branch name for dev environment
develop:
  user: www-data
  hostname: dev1.rt.gw
  stage: develop
  deploy_path: /opt/easyengine/sites/develop-ci.dev1.rt.gw/app/htdocs
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no

# Deploy Script options
ci_script_options:
  vip: false
  wp-version: latest
  slack-channel: test
