# GH branch name
master:

  # server to deploy this branch.
  hostname: dev1.rt.gw

  # user to use in deploy.
  user: root

  # branch name
  stage: master
  
  # Path to deploy.
  deploy_path: /opt/easyengine/sites/ci.dev1.rt.gw/app/htdocs

  # Setting these options because of ssh-issues in GH actions.
  # Should not be needed in future, hopefully :fingers-crossed:
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no

# GH branch name
develop:

  # server to deploy this branch.
  hostname: dev1.rt.gw

  # user to use in deploy.
  user: root

  # branch name
  stage: develop
  deploy_path: /opt/easyengine/sites/develop-ci.dev1.rt.gw/app/htdocs

  # Setting these options because of ssh-issues in GH actions.
  # Should not be needed in future, hopefully :fingers-crossed:
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no

# Deploy Script options
ci_script_options:
  vip: false
  wp-version: latest
  slack-channel: test
