on:
  schedule:
    - cron:  '0 0 * * 0'
name: WP Plugin Auto Update
jobs:
  WPAutoUpdate:
    name: WP plugin auto update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: "develop"
    - name: WP plugin auto update
      uses: docker://rtcamp/action-plugin-update:master
      env:
        WP_BOT_TOKEN: ${{ secrets.WP_BOT_TOKEN }}
        REFERENCE_BRANCH: "develop"
